export enum IssueType {
    ADDRESS_RECIPIENT = 'ADDRESS_RECIPIENT',
    PICKUP = 'PICKUP',
    PACKAGING_DAMAGE = 'PACKAGING_DAMAGE',
    PROHIBITED_RESTRICTED = 'PROHIBITED_RESTRICTED',
    PAYMENT_FRAUD = 'PAYMENT_FRAUD',
    OPERATIONAL_HUB = 'OPERATIONAL_HUB',
    DELIVERY_PROOF = 'DELIVERY_PROOF',
    RETURNS = 'RETURNS',
    INSURANCE_CLAIMS = 'INSURANCE_CLAIMS',
    COMPLIANCE = 'COMPLIANCE',
    PARTNER_LINEHAUL = 'PARTNER_LINEHAUL',
    TECH_RELIABILITY = 'TECH_RELIABILITY',
    OTHER = 'OTHER',
}

export enum IssueStatus {
    OPEN = 'OPEN',
    IN_PROGRESS = 'IN_PROGRESS',
    RESOLVED = 'RESOLVED',
    CLOSED = 'CLOSED',
    ESCALATED = 'ESCALATED',
}







